version: '3.8'
services:
  api:
    build: .
    container_name: nestjs-app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/management
      - JWT_SECRET=my-secret
    depends_on:
      - db
    networks:
      - app
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: management
    networks:
      - app
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    networks:
      - app
networks:
  app:
    driver: bridge